# Generated by Django 6.0.7 on 2026-07-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('session_key', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['query', 'created_at'], name='analytics_s_query_69e069_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('referrer', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=32)),
                ('read_seconds', models.PositiveIntegerField(default=0, help_text='Dwell time reported by the client.')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='articles.article')),
            ],
            options={
                'indexes': [models.Index(fields=['article', 'created_at'], name='analytics_p_article_d5ac36_idx')],
            },
        ),
    ]
