# Generated by Django 6.0.7 on 2026-07-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, help_text='Overrides the <title> tag. Keep under ~60 chars.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text="The <meta name='description'> snippet. ~150–160 chars.", max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords (low SEO weight today, kept for completeness).', max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Set when this content also lives at another canonical URL.')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph / Twitter card image (falls back to featured image).', null=True, upload_to='seo/og/')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(help_text="URL segment, e.g. 'politics'.", max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent section for nesting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('order', 'name'),
                'indexes': [models.Index(fields=['parent', 'order'], name='categories__parent__c62af0_idx')],
            },
        ),
    ]
