# Generated by Django 6.0.7 on 2026-07-21 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sources', models.JSONField(default=list, help_text='Source slugs included in this run.')),
                ('dry_run', models.BooleanField(default=False)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('detail', models.JSONField(default=dict)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AggregatedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(db_index=True, help_text="Source slug, e.g. 'nation'.", max_length=64)),
                ('source_name', models.CharField(help_text="Human-readable source, e.g. 'Nation Africa'.", max_length=120)),
                ('region', models.CharField(choices=[('kenya', 'Kenya'), ('international', 'International'), ('global', 'Global (API)')], db_index=True, max_length=16)),
                ('external_id', models.CharField(max_length=500)),
                ('url', models.URLField(help_text='Canonical link to the original story.', max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, help_text='Short standfirst/summary from the feed.')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, help_text='Remote lead image, if the feed provides one.', max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_hidden', models.BooleanField(db_index=True, default=False, help_text='Excluded from the working queue.')),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('imported_article', models.ForeignKey(blank=True, help_text='Set once this item has been imported into an editorial Article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.article')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['source', 'is_hidden'], name='aggregation_source_3c11ea_idx'), models.Index(fields=['region', 'is_hidden'], name='aggregation_region_99d9a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_agg_source_external')],
            },
        ),
    ]
