# Generated by Django 6.0.7 on 2026-07-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedarticle',
            name='content',
            field=models.TextField(blank=True, help_text='Extracted full-article HTML, if fetched.'),
        ),
        migrations.AddField(
            model_name='aggregatedarticle',
            name='content_fetched',
            field=models.BooleanField(default=False, help_text='Full-content extraction has been attempted.'),
        ),
    ]
