# Generated by Django 6.0.7 on 2026-08-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0002_aggregatedarticle_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedarticle',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
