# Generated by Django 6.0.7 on 2026-08-03 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aggregation', '0002_aggregatedarticle_content_and_more'),
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SynthesisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('angle', models.CharField(blank=True, help_text='Optional editorial steer for the framing of the piece.', max_length=300)),
                ('category_slug', models.CharField(blank=True, help_text='Editorial section the resulting draft is filed under.', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], db_index=True, default='pending', max_length=12)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('article', models.ForeignKey(blank=True, help_text='The draft article this job produced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synthesis_job', to='articles.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synthesis_jobs', to=settings.AUTH_USER_MODEL)),
                ('sources', models.ManyToManyField(help_text='The aggregated items fed into this synthesis.', related_name='synthesis_jobs', to='aggregation.aggregatedarticle')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='synthesis_s_status_7d2e8a_idx')],
            },
        ),
    ]
