# Generated by Django 6.0.7 on 2026-07-20 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, help_text='Overrides the <title> tag. Keep under ~60 chars.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text="The <meta name='description'> snippet. ~150–160 chars.", max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords (low SEO weight today, kept for completeness).', max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Set when this content also lives at another canonical URL.')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph / Twitter card image (falls back to featured image).', null=True, upload_to='seo/og/')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbs/%Y/%m/')),
                ('video_file', models.FileField(upload_to='videos/source/%Y/%m/')),
                ('hls_playlist', models.CharField(blank=True, help_text='Path/URL to .m3u8 master playlist.', max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='categories.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='categories.tag')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
