# Generated by Django 6.0.7 on 2026-07-20 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('placement', models.CharField(choices=[('header', 'Header'), ('sidebar', 'Sidebar'), ('in_content', 'In-content'), ('mobile', 'Mobile'), ('popup', 'Popup')], db_index=True, max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('html', models.TextField(blank=True, help_text='Raw ad markup, used when no image is set.')),
                ('target_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['placement', 'is_active'], name='ads_adverti_placeme_f84cba_idx')],
            },
        ),
    ]
