# Generated by Django 6.0.7 on 2026-07-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='effect',
            field=models.CharField(choices=[('none', 'None'), ('pulse', 'Pulse (gentle)'), ('glow', 'Glow'), ('blink', 'Blink')], default='none', help_text='High-visibility animation for the ad.', max_length=8),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='overlay_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='bottom', max_length=8),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='overlay_text',
            field=models.CharField(blank=True, help_text='Optional words shown on top of the image.', max_length=120),
        ),
    ]
