# Generated by Django 6.0.7 on 2026-07-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertisement_effect_advertisement_overlay_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='left_text',
            field=models.CharField(blank=True, help_text='Text to the left of a header/in-content banner image.', max_length=120),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='right_text',
            field=models.CharField(blank=True, help_text='Text to the right of a header/in-content banner image.', max_length=120),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='overlay_text',
            field=models.CharField(blank=True, help_text='Optional words shown on top of the image (other placements).', max_length=120),
        ),
    ]
