# Generated by Django 6.0.7 on 2026-07-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_advertisement_left_text_advertisement_right_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image_fit',
            field=models.CharField(choices=[('contain', 'Contain (whole image)'), ('cover', 'Cover (fill, may crop)')], default='contain', help_text='How the image fills its slot: contain (whole image) or cover (fill, may crop).', max_length=8),
        ),
    ]
