# Generated by Django 6.0.7 on 2026-07-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-is_default', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LiveChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField(help_text='Embed or stream URL.')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='live/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('yes_votes', models.PositiveIntegerField(default=0)),
                ('no_votes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Flash News', max_length=120)),
                ('contact_email', models.EmailField(default='contact@flashnews.dev', max_length=254)),
                ('news_ticker_total', models.PositiveIntegerField(default=10)),
                ('video_item_total', models.PositiveIntegerField(default=6)),
                ('theme_color_1', models.CharField(default='#4f63d2', max_length=9)),
                ('theme_color_2', models.CharField(default='#1dc175', max_length=9)),
                ('google_analytics_id', models.CharField(blank=True, max_length=40)),
                ('disqus_code', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('date_status', models.BooleanField(default=True)),
                ('email_status', models.BooleanField(default=True)),
                ('news_ticker_status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site setting',
            },
        ),
        migrations.CreateModel(
            name='SocialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(help_text="Icon class, e.g. 'fab fa-facebook-f'.", max_length=60)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('about', 'About'), ('contact', 'Contact'), ('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy'), ('disclaimer', 'Disclaimer'), ('faq', 'FAQ')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
    ]
