# Generated by Django 6.0.7 on 2026-07-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_us',
            field=models.TextField(blank=True, default='Flash News is a demo news platform built as a full-stack learning project — covering the backend API, SEO, the website, and the mobile app.', help_text="Short 'About Us' blurb shown in the site footer."),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
