# Generated by Django 6.0.7 on 2026-07-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_path', models.CharField(db_index=True, max_length=500)),
                ('size', models.CharField(choices=[('thumbnail', 'Thumbnail'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=16)),
                ('image_format', models.CharField(choices=[('webp', 'WebP'), ('avif', 'AVIF'), ('jpeg', 'JPEG')], max_length=8)),
                ('file', models.ImageField(upload_to='renditions/%Y/%m/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('bytes', models.PositiveIntegerField(help_text='File size in bytes.')),
            ],
            options={
                'indexes': [models.Index(fields=['source_path'], name='media_image_source__9f0b92_idx')],
                'unique_together': {('source_path', 'size', 'image_format')},
            },
        ),
    ]
