# Generated by Django 6.0.7 on 2026-07-20 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, help_text='Overrides the <title> tag. Keep under ~60 chars.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text="The <meta name='description'> snippet. ~150–160 chars.", max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords (low SEO weight today, kept for completeness).', max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Set when this content also lives at another canonical URL.')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph / Twitter card image (falls back to featured image).', null=True, upload_to='seo/og/')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('ended', 'Ended')], db_index=True, default='upcoming', max_length=16)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_blogs', to='categories.category')),
            ],
            options={
                'ordering': ('-starts_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LiveBlogUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_pinned', models.BooleanField(default=False, help_text='Keep at top (e.g. key result).')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_updates', to=settings.AUTH_USER_MODEL)),
                ('live_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='livecoverage.liveblog')),
            ],
            options={
                'ordering': ('-is_pinned', '-created_at'),
                'indexes': [models.Index(fields=['live_blog', '-created_at'], name='livecoverag_live_bl_d65891_idx')],
            },
        ),
    ]
